TRUNCATE TABLE Persons;
INSERT INTO Persons (FirstName, LastName, DateOfBirth, Sex, ImagePath) VALUES ('Benedick', 'Felten', '10/19/1993', 'M', '');
INSERT INTO Persons (FirstName, LastName, DateOfBirth, Sex, ImagePath) VALUES ('Emmet', 'Gimlet', '10/7/1999', 'M', '');
INSERT INTO Persons (FirstName, LastName, DateOfBirth, Sex, ImagePath) VALUES ('Rosina', 'Chanatier', '7/21/1995', 'F', '');
INSERT INTO Persons (FirstName, LastName, DateOfBirth, Sex, ImagePath) VALUES ('Camila', 'Glancey', '6/11/1994', 'F', '');
INSERT INTO Persons (FirstName, LastName, DateOfBirth, Sex, ImagePath) VALUES ('Brandon', 'Rostein', '1/28/1991', 'M', '');
INSERT INTO Persons (FirstName, LastName, DateOfBirth, Sex, ImagePath) VALUES ('Sebastia', 'Sindall', '1/7/1974', 'M', '');
INSERT INTO Persons (FirstName, LastName, DateOfBirth, Sex, ImagePath) VALUES ('Myrella', 'Alpeth', '4/21/2004', 'F', '');
INSERT INTO Persons (FirstName, LastName, DateOfBirth, Sex, ImagePath) VALUES ('Silvie', 'Corvino', '6/27/1992', 'F', '');
INSERT INTO Persons (FirstName, LastName, DateOfBirth, Sex, ImagePath) VALUES ('Robert', 'Klein', '12/18/1987', 'M', '');
INSERT INTO Persons (FirstName, LastName, DateOfBirth, Sex, ImagePath) VALUES ('Benjamin', 'Batteur', '1/30/1995', 'M', '');
INSERT INTO Persons (FirstName, LastName, DateOfBirth, Sex, ImagePath) VALUES ('Trudy', 'Kinnin', '6/9/1985', 'F', '');
INSERT INTO Persons (FirstName, LastName, DateOfBirth, Sex, ImagePath) VALUES ('Jayne', 'Arends', '8/16/1996', 'F', '');
INSERT INTO Persons (FirstName, LastName, DateOfBirth, Sex, ImagePath) VALUES ('Humbert', 'Heikin', '10/14/1991', 'M', '');
INSERT INTO Persons (FirstName, LastName, DateOfBirth, Sex, ImagePath) VALUES ('Christian', 'Pack', '4/6/1995', 'M', '');
INSERT INTO Persons (FirstName, LastName, DateOfBirth, Sex, ImagePath) VALUES ('Marcela', 'Gamon', '8/21/2002', 'F', '');
INSERT INTO Persons (FirstName, LastName, DateOfBirth, Sex, ImagePath) values ('Luca', 'Sevior', '9/20/2019', 'M');
INSERT INTO Persons (FirstName, LastName, DateOfBirth, Sex, ImagePath) values ('Andrea', 'Leavry', '4/23/1978', 'F');
INSERT INTO Persons (FirstName, LastName, DateOfBirth, Sex, ImagePath) values ('Verina', 'Merlus', '3/14/1998', 'F');
INSERT INTO Persons (FirstName, LastName, DateOfBirth, Sex, ImagePath) values ('Torey', 'Bradfort', '8/11/1991', 'F');
INSERT INTO Persons (FirstName, LastName, DateOfBirth, Sex, ImagePath) values ('Vita', 'Pizzella', '7/11/2020', 'F');
